version: '3'

services:
  service:
    container_name: service
    build: .
    command: /code/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - test_db
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
  test_db:
    container_name: test_db
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379