# Generated by Django 4.2.1 on 2023-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_3', '0002_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
